// Comprehensive EA FC Player Database generated from spreadsheet
const PLAYERS_DATABASE = [
    {
        "id": "p_1",
        "name": "Thibaut Courtois",
        "category": "Goalkeepers (GK)",
        "basePrice": "₹5M",
        "nation": "BELGIUM",
        "flagImg": "Flag_of_Belgium.svg",
        "pos": "GK",
        "rating": 89,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Thibaut Courtois.png"
    },
    {
        "id": "p_2",
        "name": "Gianluigi Donnarumma",
        "category": "Goalkeepers (GK)",
        "basePrice": "₹5M",
        "nation": "ITALY",
        "flagImg": "Flag_of_Italy.svg",
        "pos": "GK",
        "rating": 89,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gianluigi Donnarumma.png"
    },
    {
        "id": "p_3",
        "name": "Alisson",
        "category": "Goalkeepers (GK)",
        "basePrice": "₹5M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "GK",
        "rating": 89,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Alison.png"
    },
    {
        "id": "p_4",
        "name": "Jan Oblak",
        "category": "Goalkeepers (GK)",
        "basePrice": "₹5M",
        "nation": "SLOVENIA",
        "flagImg": "Flag_of_Slovenia.svg",
        "pos": "GK",
        "rating": 88,
        "club": "ATLETICO MADRID",
        "clubImg": "Atletico_Madrid_Logo_2024.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Jan Oblak.png"
    },
    {
        "id": "p_5",
        "name": "Mike Maignan",
        "category": "Goalkeepers (GK)",
        "basePrice": "₹5M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "GK",
        "rating": 87,
        "club": "AC MILAN",
        "clubImg": "AC_Milan_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Mike Maignan.png"
    },
    {
        "id": "p_6",
        "name": "David Raya",
        "category": "Goalkeepers (GK)",
        "basePrice": "₹5M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "GK",
        "rating": 87,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/David Raya.png"
    },
    {
        "id": "p_7",
        "name": "Virgil Van Dijk",
        "category": "Centre Backs (CB)",
        "basePrice": "₹10M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "CB",
        "rating": 90,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Virgil Van Dijk.png"
    },
    {
        "id": "p_8",
        "name": "William Saliba",
        "category": "Centre Backs (CB)",
        "basePrice": "₹5M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "CB",
        "rating": 87,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/William Saliba.png"
    },
    {
        "id": "p_9",
        "name": "Gabriel",
        "category": "Centre Backs (CB)",
        "basePrice": "₹7.5M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CB",
        "rating": 88,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gabriel.png"
    },
    {
        "id": "p_10",
        "name": "Alessandro Bastoni",
        "category": "Centre Backs (CB)",
        "basePrice": "₹5M",
        "nation": "ITALY",
        "flagImg": "Flag_of_Italy.svg",
        "pos": "CB",
        "rating": 87,
        "club": "INTER MILAN",
        "clubImg": "FC_Internazionale_Milano_2021.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Bastoni.png"
    },
    {
        "id": "p_11",
        "name": "Ruben Dias",
        "category": "Centre Backs (CB)",
        "basePrice": "₹5M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CB",
        "rating": 86,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Ruben Dias.png"
    },
    {
        "id": "p_12",
        "name": "Marquinhos",
        "category": "Centre Backs (CB)",
        "basePrice": "₹7.5M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CB",
        "rating": 87,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Marquinhos .png"
    },
    {
        "id": "p_13",
        "name": "Ibrahima Konate",
        "category": "Centre Backs (CB)",
        "basePrice": "₹5M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "CB",
        "rating": 86,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Ibrahim Konate.png"
    },
    {
        "id": "p_14",
        "name": "Antonio Rudiger",
        "category": "Centre Backs (CB)",
        "basePrice": "₹5M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CB",
        "rating": 86,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Rudiger.png"
    },
    {
        "id": "p_15",
        "name": "Dayot Upamecano",
        "category": "Centre Backs (CB)",
        "basePrice": "₹2M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "CB",
        "rating": 85,
        "club": "BAYERN MUNICH",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Dayot Upamecano.png"
    },
    {
        "id": "p_16",
        "name": "Ronald Araujo",
        "category": "Centre Backs (CB)",
        "basePrice": "₹2M",
        "nation": "URUGUAY",
        "flagImg": "Flag_of_Uruguay.svg",
        "pos": "CB",
        "rating": 85,
        "club": "FC BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Ronald Araujo.png"
    },
    {
        "id": "p_17",
        "name": "Jonathan Tah",
        "category": "Centre Backs (CB)",
        "basePrice": "₹5M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CB",
        "rating": 87,
        "club": "BAYER LEVERKUSEN",
        "clubImg": "Bayer_Leverkusen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Jonnathan Tah.png"
    },
    {
        "id": "p_18",
        "name": "William Pacho",
        "category": "Centre Backs (CB)",
        "basePrice": "₹5M",
        "nation": "ECUADOR",
        "flagImg": "Flag_of_Ecuador.svg",
        "pos": "CB",
        "rating": 86,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/William Pacho.png"
    },
    {
        "id": "p_19",
        "name": "Nico Schlotterbeck",
        "category": "Centre Backs (CB)",
        "basePrice": "₹1M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CB",
        "rating": 85,
        "club": "BORUSSIA DORTMUND",
        "clubImg": "Borussia_Dortmund_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Schlotterbeck.png"
    },
    {
        "id": "p_20",
        "name": "Bremer",
        "category": "Centre Backs (CB)",
        "basePrice": "₹1M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CB",
        "rating": 85,
        "club": "JUVENTUS",
        "clubImg": "Serie_A_ENILIVE_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Bremer .png"
    },
    {
        "id": "p_21",
        "name": "Eder Militao",
        "category": "Centre Backs (CB)",
        "basePrice": "₹1M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CB",
        "rating": 84,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Eder Militao.png"
    },
    {
        "id": "p_22",
        "name": "Achraf Hakimi",
        "category": "Right Backs (RB)",
        "basePrice": "₹10M",
        "nation": "MOROCCO",
        "flagImg": "Flag_of_Morocco.svg",
        "pos": "RB",
        "rating": 89,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Achraf Hakimi.png"
    },
    {
        "id": "p_23",
        "name": "Trent Alexander-Arnold",
        "category": "Right Backs (RB)",
        "basePrice": "₹7.5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "RB",
        "rating": 86,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Trent Alexander Arnorld.png"
    },
    {
        "id": "p_24",
        "name": "Jules Kounde",
        "category": "Right Backs (RB)",
        "basePrice": "₹7.5M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "RB",
        "rating": 87,
        "club": "FC BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Kounde.png"
    },
    {
        "id": "p_25",
        "name": "Jeremie Frimpong",
        "category": "Right Backs (RB)",
        "basePrice": "₹5M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "RB",
        "rating": 86,
        "club": "BAYER LEVERKUSEN",
        "clubImg": "Bayer_Leverkusen_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Jeremie Frimpong.png"
    },
    {
        "id": "p_26",
        "name": "Denzel Dumfries",
        "category": "Right Backs (RB)",
        "basePrice": "₹3M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "RB",
        "rating": 84,
        "club": "INTER MILAN",
        "clubImg": "FC_Internazionale_Milano_2021.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Denzel Dumfries.png"
    },
    {
        "id": "p_27",
        "name": "Marcos Llorente",
        "category": "Right Backs (RB)",
        "basePrice": "₹3M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "RB",
        "rating": 84,
        "club": "ATLETICO MADRID",
        "clubImg": "Atletico_Madrid_Logo_2024.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Marcos Llorente.png"
    },
    {
        "id": "p_28",
        "name": "Nuno Mendes",
        "category": "Left Backs (LB)",
        "basePrice": "₹10M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "LB",
        "rating": 88,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Nuno Mendes.png"
    },
    {
        "id": "p_29",
        "name": "Josko Gvardiol",
        "category": "Left Backs (LB)",
        "basePrice": "₹5M",
        "nation": "CROATIA",
        "flagImg": "Flag_of_Croatia.svg",
        "pos": "LB",
        "rating": 85,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gvardiol.png"
    },
    {
        "id": "p_30",
        "name": "Alphonso Davies",
        "category": "Left Backs (LB)",
        "basePrice": "₹5M",
        "nation": "CANADA",
        "flagImg": "Flag_of_Canada_(Pantone).svg",
        "pos": "LB",
        "rating": 84,
        "club": "BAYERN MUNICH",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Alphonso Davies.png"
    },
    {
        "id": "p_31",
        "name": "Theo Hernandez",
        "category": "Left Backs (LB)",
        "basePrice": "₹7.5M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "LB",
        "rating": 87,
        "club": "AC MILAN",
        "clubImg": "AC_Milan_logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Theo Hernandez.png"
    },
    {
        "id": "p_32",
        "name": "Marc Cucurella",
        "category": "Left Backs (LB)",
        "basePrice": "₹5M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "LB",
        "rating": 84,
        "club": "CHELSEA",
        "clubImg": "Chelsea_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Marc Cucurella.png"
    },
    {
        "id": "p_33",
        "name": "Balde",
        "category": "Left Backs (LB)",
        "basePrice": "₹1M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "LB",
        "rating": 81,
        "club": "FC BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Balde.png"
    },
    {
        "id": "p_34",
        "name": "Rodri",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "₹7.5M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "CDM",
        "rating": 90,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Rodri.png"
    },
    {
        "id": "p_35",
        "name": "Kimmich",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "₹7.5M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CDM",
        "rating": 89,
        "club": "BAYERN MUNICH",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Joshua Kimmich.png"
    },
    {
        "id": "p_36",
        "name": "Declan Rice",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "₹5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "CDM",
        "rating": 88,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Rice.png"
    },
    {
        "id": "p_37",
        "name": "Moises Caicedo",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "₹5M",
        "nation": "ECUADOR",
        "flagImg": "Flag_of_Ecuador.svg",
        "pos": "CDM",
        "rating": 88,
        "club": "CHELSEA",
        "clubImg": "Chelsea_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Caicedo.png"
    },
    {
        "id": "p_38",
        "name": "Sandro Tonali",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "₹3M",
        "nation": "ITALY",
        "flagImg": "Flag_of_Italy.svg",
        "pos": "CDM",
        "rating": 86,
        "club": "NEWCASTLE UNITED",
        "clubImg": "Newcastle_United_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Tonali.png"
    },
    {
        "id": "p_39",
        "name": "Ryan Gravenberch",
        "category": "Defensive Midfielders (CDM)",
        "basePrice": "₹3M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "CDM",
        "rating": 86,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gravenberch.png"
    },
    {
        "id": "p_40",
        "name": "Pedri",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹7.5M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "CM",
        "rating": 90,
        "club": "FC BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Pedri.png"
    },
    {
        "id": "p_41",
        "name": "Kevin De Bruyne",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹5M",
        "nation": "BELGIUM",
        "flagImg": "Flag_of_Belgium.svg",
        "pos": "CM",
        "rating": 87,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Kevin De Bruyne.png"
    },
    {
        "id": "p_42",
        "name": "Federico Valverde",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹7.5M",
        "nation": "URUGUAY",
        "flagImg": "Flag_of_Uruguay.svg",
        "pos": "CM",
        "rating": 89,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Frederico Valverde.png"
    },
    {
        "id": "p_43",
        "name": "Martin Odegaard",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹5M",
        "nation": "NORWAY",
        "flagImg": "Flag_of_Norway.svg",
        "pos": "CM",
        "rating": 87,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Martin Odegard.png"
    },
    {
        "id": "p_44",
        "name": "Bernardo Silva",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹5M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CM",
        "rating": 88,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bernardo Silva.png"
    },
    {
        "id": "p_45",
        "name": "Vitinha",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹7.5M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CM",
        "rating": 90,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Vitinha.png"
    },
    {
        "id": "p_46",
        "name": "Frenkie De Jong",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹5M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "CM",
        "rating": 87,
        "club": "FC BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Frankie De Jong.png"
    },
    {
        "id": "p_47",
        "name": "Nicolo Barella",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹5M",
        "nation": "ITALY",
        "flagImg": "Flag_of_Italy.svg",
        "pos": "CM",
        "rating": 87,
        "club": "INTER MILAN",
        "clubImg": "FC_Internazionale_Milano_2021.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Nicolo Barella.png"
    },
    {
        "id": "p_48",
        "name": "Bruno Guimaraes",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹5M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "CM",
        "rating": 86,
        "club": "NEWCASTLE UNITED",
        "clubImg": "Newcastle_United_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bruno Guimaraes.png"
    },
    {
        "id": "p_49",
        "name": "Joao Neves",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹2M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CM",
        "rating": 85,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Joao Neves.png"
    },
    {
        "id": "p_50",
        "name": "Alexis Mac Allister",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹5M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "CM",
        "rating": 87,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Alexis Mac Allister.png"
    },
    {
        "id": "p_51",
        "name": "Tijjani Reijnders",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹3M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "CM",
        "rating": 86,
        "club": "AC MILAN",
        "clubImg": "AC_Milan_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Reijnders.png"
    },
    {
        "id": "p_52",
        "name": "Enzo Fernandez",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹2M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "CM",
        "rating": 85,
        "club": "CHELSEA",
        "clubImg": "Chelsea_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Enzo Fernandez.png"
    },
    {
        "id": "p_53",
        "name": "Scott McTominay",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹1M",
        "nation": "SCOTLAND",
        "flagImg": "Flag_of_Scotland.svg",
        "pos": "CM",
        "rating": 85,
        "club": "NAPOLI",
        "clubImg": "Serie_A_ENILIVE_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Scott Mctominay.png"
    },
    {
        "id": "p_54",
        "name": "Youri Tielemans",
        "category": "Central Midfielders (CM)",
        "basePrice": "₹1M",
        "nation": "BELGIUM",
        "flagImg": "Flag_of_Belgium.svg",
        "pos": "CM",
        "rating": 84,
        "club": "ASTON VILLA",
        "clubImg": "Premier_League_Logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Youri tielmans .png"
    },
    {
        "id": "p_55",
        "name": "Jude Bellingham",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "₹10M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "CAM",
        "rating": 90,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Jude Bellingham.png"
    },
    {
        "id": "p_56",
        "name": "Florian Wirtz",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "₹7.5M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CAM",
        "rating": 89,
        "club": "BAYER LEVERKUSEN",
        "clubImg": "Bayer_Leverkusen_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Florian Wirtz.png"
    },
    {
        "id": "p_57",
        "name": "Jamal Musiala",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "₹7.5M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "CAM",
        "rating": 88,
        "club": "BAYERN MUNICH",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Jamal Musiala.png"
    },
    {
        "id": "p_58",
        "name": "Bruno Fernandes",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "₹7.5M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "CAM",
        "rating": 88,
        "club": "MANCHESTER UNITED",
        "clubImg": "Manchester_United_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bruno Fernandes.png"
    },
    {
        "id": "p_59",
        "name": "Cole Palmer",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "₹5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "CAM",
        "rating": 87,
        "club": "CHELSEA",
        "clubImg": "Chelsea_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Cole Palmer.png"
    },
    {
        "id": "p_60",
        "name": "Paulo Dybala",
        "category": "Attacking Midfielders (CAM)",
        "basePrice": "₹2M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "CAM",
        "rating": 85,
        "club": "AS ROMA",
        "clubImg": "AS_Roma_logo_(2017).svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Paulo Dybala.png"
    },
    {
        "id": "p_61",
        "name": "Vinicius Jr.",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹10M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "LW",
        "rating": 89,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Vinicius Jr.png"
    },
    {
        "id": "p_62",
        "name": "Khvicha Kvaratskhelia",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹5M",
        "nation": "GEORGIA",
        "flagImg": "Flag_of_Georgia.svg",
        "pos": "LW",
        "rating": 87,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Kvicha Kvaratskhelia.png"
    },
    {
        "id": "p_63",
        "name": "Raphinha",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹7.5M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "LW",
        "rating": 89,
        "club": "FC BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Raphinha.png"
    },
    {
        "id": "p_64",
        "name": "Nico Williams",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹5M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "LW",
        "rating": 86,
        "club": "ATHLETIC BILBAO",
        "clubImg": "Club_Athletic_Bilbao_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Nico Williams.png"
    },
    {
        "id": "p_65",
        "name": "Luis Diaz",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹5M",
        "nation": "COLOMBIA",
        "flagImg": "Flag_of_Colombia.svg",
        "pos": "LW",
        "rating": 87,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Luis Diaz.png"
    },
    {
        "id": "p_66",
        "name": "Heung-Min Son",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹5M",
        "nation": "SOUTH KOREA",
        "flagImg": "Flag_of_South_Korea.svg",
        "pos": "LW",
        "rating": 85,
        "club": "TOTTENHAM",
        "clubImg": "Premier_League_Logo.svg",
        "league": "MLS",
        "leagueImg": "Major_League_Soccer_logo.svg",
        "cardImg": "no_bg/Heung Min Son.png"
    },
    {
        "id": "p_67",
        "name": "Rafael Leao",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹5M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "LW",
        "rating": 86,
        "club": "AC MILAN",
        "clubImg": "AC_Milan_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Rafael Leao.png"
    },
    {
        "id": "p_68",
        "name": "Bradley Barcola",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹3M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "LW",
        "rating": 84,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Bradley Barcola.png"
    },
    {
        "id": "p_69",
        "name": "Cody Gakpo",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹2M",
        "nation": "NETHERLANDS",
        "flagImg": "Flag_of_the_Netherlands.svg",
        "pos": "LW",
        "rating": 84,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Cody Gakpo.png"
    },
    {
        "id": "p_70",
        "name": "Kingsley Coman",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹2M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "LW",
        "rating": 85,
        "club": "BAYERN MUNICH",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Kingsley Coman.png"
    },
    {
        "id": "p_71",
        "name": "Gabriel Martinelli",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹2M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "LW",
        "rating": 84,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Gabriel Martinelli.png"
    },
    {
        "id": "p_72",
        "name": "Anthony Gordon",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹1M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "LW",
        "rating": 84,
        "club": "NEWCASTLE UNITED",
        "clubImg": "Newcastle_United_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Anthony Gordon.png"
    },
    {
        "id": "p_73",
        "name": "Sadio Mane",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹1M",
        "nation": "SENEGAL",
        "flagImg": "Flag_of_Senegal.svg",
        "pos": "LW",
        "rating": 84,
        "club": "AL-NASSR",
        "clubImg": "Al_Hilal_SFC_Logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Sadio Mane.png"
    },
    {
        "id": "p_74",
        "name": "Leandro Trossard",
        "category": "Left Wingers / Midfielders (LW/LM)",
        "basePrice": "₹1M",
        "nation": "BELGIUM",
        "flagImg": "Flag_of_Belgium.svg",
        "pos": "LW",
        "rating": 83,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Leandro Trossard.png"
    },
    {
        "id": "p_75",
        "name": "Mohamed Salah",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹10M",
        "nation": "EGYPT",
        "flagImg": "Flag_of_Egypt.svg",
        "pos": "RW",
        "rating": 91,
        "club": "LIVERPOOL",
        "clubImg": "Liverpool_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Mohammed Salah.png"
    },
    {
        "id": "p_76",
        "name": "Lamine Yamal",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹10M",
        "nation": "SPAIN",
        "flagImg": "Flag_of_the_Kingdom_of_Spain.svg",
        "pos": "RW",
        "rating": 89,
        "club": "FC BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Lamine Yamal.png"
    },
    {
        "id": "p_77",
        "name": "Bukayo Saka",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹7.5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "RW",
        "rating": 88,
        "club": "ARSENAL",
        "clubImg": "Arsenal_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bukayo Saka.png"
    },
    {
        "id": "p_78",
        "name": "Lionel Messi",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹5M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "RW",
        "rating": 86,
        "club": "INTER MIAMI",
        "clubImg": "Inter_Miami_CF_logo.svg",
        "league": "MLS",
        "leagueImg": "Major_League_Soccer_logo.svg",
        "cardImg": "no_bg/Lionel Messi.png"
    },
    {
        "id": "p_79",
        "name": "Michael Olise",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹7.5M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "RW",
        "rating": 86,
        "club": "BAYERN MUNICH",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Michael Olise.png"
    },
    {
        "id": "p_80",
        "name": "Phil Foden",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "RW",
        "rating": 85,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Phil Foden.png"
    },
    {
        "id": "p_81",
        "name": "Desire Doue",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹5M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "RW",
        "rating": 85,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Desire Doue.png"
    },
    {
        "id": "p_82",
        "name": "Rodrygo",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹5M",
        "nation": "BRAZIL",
        "flagImg": "Flag_of_Brazil.svg",
        "pos": "RW",
        "rating": 85,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Rodrygo Goes.png"
    },
    {
        "id": "p_83",
        "name": "Bryan Mbeumo",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹2M",
        "nation": "CAMEROON",
        "flagImg": "Flag_of_Cameroon.svg",
        "pos": "RW",
        "rating": 85,
        "club": "BRENTFORD",
        "clubImg": "Premier_League_Logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Bryan Mbuemo.png"
    },
    {
        "id": "p_84",
        "name": "Christian Pulisic",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹2M",
        "nation": "USA",
        "flagImg": "Flag_of_the_United_States_(DDD-F-416E_specifications).svg",
        "pos": "RW",
        "rating": 84,
        "club": "AC MILAN",
        "clubImg": "AC_Milan_logo.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Christian Pulisic.png"
    },
    {
        "id": "p_85",
        "name": "Moussa Diaby",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹1M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "RW",
        "rating": 84,
        "club": "AL-ITTIHAD",
        "clubImg": "Al-Ittihad_Club_(Jeddah)_logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Moussa Diaby.png"
    },
    {
        "id": "p_86",
        "name": "Brahim Diaz",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹1M",
        "nation": "MOROCCO",
        "flagImg": "Flag_of_Morocco.svg",
        "pos": "RW",
        "rating": 82,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Brahim Diaz.png"
    },
    {
        "id": "p_87",
        "name": "Karim Adeyemi",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹1M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "RW",
        "rating": 84,
        "club": "BORUSSIA DORTMUND",
        "clubImg": "Borussia_Dortmund_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Schlotterbeck.png"
    },
    {
        "id": "p_88",
        "name": "Leroy Sane",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹1M",
        "nation": "GERMANY",
        "flagImg": "Flag_of_Germany.svg",
        "pos": "RW",
        "rating": 84,
        "club": "BAYERN MUNICH",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Leroy Sane.png"
    },
    {
        "id": "p_89",
        "name": "Rayan Cherki",
        "category": "Right Wingers / Midfielders (RW/RM)",
        "basePrice": "₹1M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "CAM",
        "rating": 85,
        "club": "LYON",
        "clubImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Rayan Cherki.png"
    },
    {
        "id": "p_90",
        "name": "Kylian Mbappe",
        "category": "Strikers (ST)",
        "basePrice": "₹10M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "ST",
        "rating": 91,
        "club": "REAL MADRID",
        "clubImg": "Real_Madrid_logo.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Kylian Mbappe.png"
    },
    {
        "id": "p_91",
        "name": "Erling Haaland",
        "category": "Strikers (ST)",
        "basePrice": "₹10M",
        "nation": "NORWAY",
        "flagImg": "Flag_of_Norway.svg",
        "pos": "ST",
        "rating": 91,
        "club": "MANCHESTER CITY",
        "clubImg": "Manchester_City_FC.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Erling Haaland.png"
    },
    {
        "id": "p_92",
        "name": "Harry Kane",
        "category": "Strikers (ST)",
        "basePrice": "₹7.5M",
        "nation": "ENGLAND",
        "flagImg": "Flag_of_England.svg",
        "pos": "ST",
        "rating": 90,
        "club": "BAYERN MUNICH",
        "clubImg": "FC_Bayern_Munchen_logo.svg",
        "league": "BUNDESLIGA",
        "leagueImg": "Bundesliga_logo_(2017).svg",
        "cardImg": "no_bg/Harry Kane.png"
    },
    {
        "id": "p_93",
        "name": "Ousmane Dembele",
        "category": "Strikers (ST)",
        "basePrice": "₹10M",
        "nation": "FRANCE",
        "flagImg": "Flag_of_France.svg",
        "pos": "ST",
        "rating": 90,
        "club": "PSG",
        "clubImg": "PSG_logo.svg",
        "league": "LIGUE 1",
        "leagueImg": "Logo_Ligue_1_McDonald_s_2024.svg",
        "cardImg": "no_bg/Ousmane Dembele.png"
    },
    {
        "id": "p_94",
        "name": "Lautaro Martinez",
        "category": "Strikers (ST)",
        "basePrice": "₹7.5M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "ST",
        "rating": 88,
        "club": "INTER MILAN",
        "clubImg": "FC_Internazionale_Milano_2021.svg",
        "league": "SERIE A",
        "leagueImg": "Serie_A_ENILIVE_logo.svg",
        "cardImg": "no_bg/Lautaro Martinez.png"
    },
    {
        "id": "p_95",
        "name": "Alexander Isak",
        "category": "Strikers (ST)",
        "basePrice": "₹5M",
        "nation": "SWEDEN",
        "flagImg": "Flag_of_Sweden.svg",
        "pos": "ST",
        "rating": 87,
        "club": "NEWCASTLE UNITED",
        "clubImg": "Newcastle_United_logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Alexander Isak.png"
    },
    {
        "id": "p_96",
        "name": "Viktor Gyokeres",
        "category": "Strikers (ST)",
        "basePrice": "₹5M",
        "nation": "SWEDEN",
        "flagImg": "Flag_of_Sweden.svg",
        "pos": "ST",
        "rating": 87,
        "club": "SPORTING CP",
        "clubImg": "Premier_League_Logo.svg",
        "league": "PREMIER LEAGUE",
        "leagueImg": "Premier_League_Logo.svg",
        "cardImg": "no_bg/Viktor Gyokeres.png"
    },
    {
        "id": "p_97",
        "name": "Julian Alvarez",
        "category": "Strikers (ST)",
        "basePrice": "₹5M",
        "nation": "ARGENTINA",
        "flagImg": "Flag_of_Argentina.svg",
        "pos": "ST",
        "rating": 87,
        "club": "ATLETICO MADRID",
        "clubImg": "Atletico_Madrid_Logo_2024.svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Alvarez.png"
    },
    {
        "id": "p_98",
        "name": "Robert Lewandowski",
        "category": "Strikers (ST)",
        "basePrice": "₹7.5M",
        "nation": "POLAND",
        "flagImg": "Flag_of_Poland.svg",
        "pos": "ST",
        "rating": 88,
        "club": "FC BARCELONA",
        "clubImg": "FC_Barcelona_(crest).svg",
        "league": "LALIGA",
        "leagueImg": "LaLiga_EA_Sports_2023_Vertical_Logo.svg",
        "cardImg": "no_bg/Robert Lewandowski.png"
    },
    {
        "id": "p_99",
        "name": "Cristiano Ronaldo",
        "category": "Strikers (ST)",
        "basePrice": "₹3M",
        "nation": "PORTUGAL",
        "flagImg": "Flag_of_Portugal_(official).svg",
        "pos": "ST",
        "rating": 84,
        "club": "AL-NASSR",
        "clubImg": "Al_Hilal_SFC_Logo.svg",
        "league": "SAUDI PRO LEAGUE",
        "leagueImg": "Roshn_Saudi_League_Logo.svg",
        "cardImg": "no_bg/Cristiano Ronaldo.png"
    }
];
