# Auto-generated from Mock_IPL_Auction_2026_Player_Pool.pdf
# Each entry: (lot_number, player_name, pool)

PLAYERS = [
    (1, "Virat Kohli", "A"), (2, "Rohit Sharma", "A"), (3, "Suryakumar Yadav", "A"),
    (4, "Shubman Gill", "A"), (5, "Yashasvi Jaiswal", "A"), (6, "Ruturaj Gaikwad", "A"),
    (7, "Travis Head", "A"), (8, "Shreyas Iyer", "A"), (9, "Sai Sudharsan", "A"),
    (10, "Rinku Singh", "A"), (11, "Rajat Patidar", "A"), (12, "Tilak Varma", "A"),
    (13, "David Miller", "A"), (14, "Tristan Stubbs", "A"), (15, "Rishabh Pant", "A"),
    (16, "Heinrich Klaasen", "A"), (17, "Nicholas Pooran", "A"), (18, "Sanju Samson", "A"),
    (19, "Jos Buttler", "A"), (20, "KL Rahul", "A"), (21, "Quinton de Kock", "A"),
    (22, "Ishan Kishan", "A"), (23, "Phil Salt", "A"), (24, "MS Dhoni", "A"),
    (25, "Rahmanullah Gurbaz", "A"), (26, "Jitesh Sharma", "A"), (27, "Josh Inglis", "A"),
    (28, "Dhruv Jurel", "A"), (29, "Hardik Pandya", "A"), (30, "Ravindra Jadeja", "A"),
    (31, "Cameron Green", "A"), (33, "Axar Patel", "A"), (34, "Glenn Maxwell", "A"),
    (35, "Liam Livingstone", "A"), (36, "Mitchell Marsh", "A"), (37, "Nitish Kumar Reddy", "A"),
    (38, "Marcus Stoinis", "A"), (39, "Sam Curran", "A"), (40, "Abhishek Sharma", "A"),
    (41, "Venkatesh Iyer", "A"), (42, "Washington Sundar", "A"), (43, "Jasprit Bumrah", "A"),
    (44, "Pat Cummins", "A"), (45, "Mitchell Starc", "A"), (46, "Arshdeep Singh", "A"),
    (47, "Trent Boult", "A"), (48, "Mohammed Shami", "A"), (49, "Mohammed Siraj", "A"),
    (50, "Matheesha Pathirana", "A"), (51, "Harshit Rana", "A"), (52, "Mayank Yadav", "A"),
    (53, "Prasidh Krishna", "A"), (54, "Josh Hazlewood", "A"), (55, "Jofra Archer", "A"),
    (56, "Sandeep Sharma", "A"), (57, "Rashid Khan", "A"), (58, "Yuzvendra Chahal", "A"),
    (59, "Kuldeep Yadav", "A"), (60, "Ravi Bishnoi", "A"), (61, "Varun Chakaravarthy", "A"),
    (62, "Wanindu Hasaranga", "A"), (63, "Maheesh Theekshana", "A"), (64, "Ravichandran Ashwin", "A"),
    (65, "Adam Zampa", "A"), (66, "Noor Ahmad", "A"), (67, "R Sai Kishore", "A"),
    (68, "Adil Rashid", "A"), (69, "Tabraiz Shamsi", "A"), (70, "Rahul Chahar", "A"),

    (71, "Harry Brook", "B"), (72, "Manish Pandey", "B"), (73, "Ayush Badoni", "B"),
    (74, "Nehal Wadhera", "B"), (75, "Jake Fraser-McGurk", "B"), (76, "Rovman Powell", "B"),
    (77, "Shimron Hetmyer", "B"), (78, "Aiden Markram", "B"), (79, "Tim David", "B"),
    (80, "Glenn Phillips", "B"), (81, "Devdutt Padikkal", "B"), (82, "Prithvi Shaw", "B"),
    (83, "Rahul Tripathi", "B"), (84, "Kane Williamson", "B"), (85, "Prabhsimran Singh", "B"),
    (86, "Ryan Rickelton", "B"), (87, "Shai Hope", "B"), (88, "Kusal Mendis", "B"),
    (89, "Matthew Wade", "B"), (90, "KS Bharat", "B"), (91, "Anuj Rawat", "B"),
    (92, "Litton Das", "B"), (93, "Upendra Yadav", "B"), (94, "Donovan Ferreira", "B"),
    (95, "Tom Banton", "B"), (96, "B.R. Sharath", "B"), (97, "Vishnu Vinod", "B"),
    (98, "Abishek Porel", "B"), (99, "Jonny Bairstow", "B"), (100, "Marco Jansen", "B"),
    (101, "Romario Shepherd", "B"), (102, "Deepak Hooda", "B"), (103, "Krunal Pandya", "B"),
    (104, "Shardul Thakur", "B"), (105, "Vijay Shankar", "B"), (106, "Shivam Dube", "B"),
    (107, "Riyan Parag", "B"), (108, "Jason Holder", "B"), (109, "Azmatullah Omarzai", "B"),
    (110, "Moeen Ali", "B"), (111, "Sherfane Rutherford", "B"), (112, "Daryl Mitchell", "B"),
    (113, "Harshal Patel", "B"), (114, "Avesh Khan", "B"), (115, "Khaleel Ahmed", "B"),
    (116, "Tushar Deshpande", "B"), (117, "Mukesh Kumar", "B"), (118, "Deepak Chahar", "B"),
    (119, "Lockie Ferguson", "B"), (120, "Alzarri Joseph", "B"), (121, "Spencer Johnson", "B"),
    (122, "Nandre Burger", "B"), (123, "Naveen-ul-Haq", "B"), (124, "Yash Dayal", "B"),
    (125, "Fazalhaq Farooqi", "B"), (126, "T Natarajan", "B"), (127, "R Sai Kishore", "B"),
    (128, "Piyush Chawla", "B"), (129, "Mayank Markande", "B"), (130, "Amit Mishra", "B"),
    (131, "Karn Sharma", "B"), (132, "Suyash Sharma", "B"), (133, "Mitchell Santner", "B"),
    (134, "Mujeeb Ur Rahman", "B"), (135, "Keshav Maharaj", "B"), (136, "Gudakesh Motie", "B"),
    (137, "Allah Ghazanfar", "B"), (138, "Waqar Salamkheil", "B"), (139, "Qais Ahmad", "B"),
    (140, "Viyaskanth Vijayakanth", "B"),

    (141, "Ajinkya Rahane", "C"), (142, "Mayank Agarwal", "C"), (143, "Nitish Rana", "C"),
    (144, "Shahrukh Khan", "C"), (145, "Angkrish Raghuvanshi", "C"), (146, "Sameer Rizvi", "C"),
    (147, "Abhinav Manohar", "C"), (148, "Karun Nair", "C"), (149, "Jason Roy", "C"),
    (150, "Finn Allen", "C"), (151, "Steve Smith", "C"), (152, "Bhanuka Rajapaksa", "C"),
    (153, "Sarfaraz Khan", "C"), (154, "Joe Root", "C"), (155, "Narayan Jagadeesan", "C"),
    (156, "Luvnith Sisodia", "C"), (157, "Harvik Desai", "C"), (158, "Tom Kohler-Cadmore", "C"),
    (159, "Sam Billings", "C"), (160, "Tim Seifert", "C"), (161, "Andre Fletcher", "C"),
    (162, "Johnson Charles", "C"), (163, "Ben McDermott", "C"), (164, "Lorcan Tucker", "C"),
    (165, "Alex Carey", "C"), (166, "Scott Edwards", "C"), (167, "Mohammad Haris", "C"),
    (168, "Sheldon Jackson", "C"), (169, "Naman Dhir", "C"), (170, "Shahbaz Ahmed", "C"),
    (171, "Krishnappa Gowtham", "C"), (172, "Anshul Kamboj", "C"), (173, "Mahipal Lomror", "C"),
    (174, "Sanvir Singh", "C"), (175, "Daniel Sams", "C"), (176, "Sikandar Raza", "C"),
    (177, "Wian Mulder", "C"), (178, "Fabian Allen", "C"), (179, "Karim Janat", "C"),
    (180, "Mohammad Nabi", "C"), (181, "Dasun Shanaka", "C"), (182, "Jimmy Neesham", "C"),
    (183, "Umran Malik", "C"), (184, "Chetan Sakariya", "C"), (185, "Kamlesh Nagarkoti", "C"),
    (186, "Yash Thakur", "C"), (187, "Rasikh Dar", "C"), (188, "Mohit Sharma", "C"),
    (189, "Jhye Richardson", "C"), (190, "Dilshan Madushanka", "C"), (191, "Lance Morris", "C"),
    (192, "Reece Topley", "C"), (193, "Richard Ngarava", "C"), (194, "Umesh Yadav", "C"),
    (195, "Ishant Sharma", "C"), (196, "Jaydev Unadkat", "C"), (197, "Manav Suthar", "C"),
    (198, "Kumar Kartikeya", "C"), (199, "Hrithik Shokeen", "C"), (200, "Mayank Dagar", "C"),
    (201, "Jagadeesha Suchith", "C"), (202, "Ish Sodhi", "C"), (203, "Dunith Wellalage", "C"),
    (204, "Ayan Afzal Khan", "C"), (205, "Jeffrey Vandersay", "C"), (206, "Pravin Dubey", "C"),
    (207, "Zahir Khan", "C"), (208, "Sandeep Lamichhane", "C"), (209, "Prabath Jayasuriya", "C"),
    (210, "Lakshan Sandakan", "C"),

    (211, "Shashank Singh", "D"), (212, "Ashutosh Sharma", "D"), (213, "Yash Dhull", "D"),
    (214, "Priyam Garg", "D"), (215, "Anmolpreet Singh", "D"), (216, "Subhranshu Senapati", "D"),
    (217, "Musheer Khan", "D"), (218, "Ripal Patel", "D"), (219, "C. Hari Nishaanth", "D"),
    (220, "Swastik Chikara", "D"), (221, "Aaron Jones", "D"), (222, "Steven Taylor", "D"),
    (223, "George Munsey", "D"), (224, "Monank Patel", "D"), (225, "Kumar Kushagra", "D"),
    (226, "Robin Minz", "D"), (227, "Avanish Rao Aravelly", "D"), (228, "Urvil Patel", "D"),
    (229, "Sumit Kumar", "D"), (230, "Ricky Bhui", "D"), (231, "Aryan Juyal", "D"),
    (232, "Fazal Niyaz", "D"), (233, "Andries Gous", "D"), (234, "Michael Jones", "D"),
    (235, "Vriitya Aravind", "D"), (236, "Nicholas Welch", "D"), (237, "Clive Madande", "D"),
    (238, "Lhuan-dre Pretorius", "D"), (239, "Tanush Kotian", "D"), (240, "Anukul Roy", "D"),
    (241, "Vivrant Sharma", "D"), (242, "Prerak Mankad", "D"), (243, "Ramandeep Singh", "D"),
    (244, "Rajangad Bawa", "D"), (245, "Nishant Sindhu", "D"), (246, "Harsh Tyagi", "D"),
    (247, "Aman Khan", "D"), (248, "Gerhard Erasmus", "D"), (249, "Logan van Beek", "D"),
    (250, "Brandon McMullen", "D"), (251, "Harmeet Singh", "D"), (252, "Bas de Leede", "D"),
    (253, "Vidwath Kaverappa", "D"), (254, "Vyshak Vijaykumar", "D"), (255, "Akash Madhwal", "D"),
    (256, "Kuldeep Sen", "D"), (257, "Kartik Tyagi", "D"), (258, "K.M. Asif", "D"),
    (259, "Yudhvir Singh Charak", "D"), (260, "Eshan Malinga", "D"), (261, "Saurabh Netravalkar", "D"),
    (262, "Ali Khan", "D"), (263, "Bilal Khan", "D"), (264, "Bradley Currie", "D"),
    (265, "Sakib Hussain", "D"), (266, "Gurjapneet Singh", "D"), (267, "M. Siddharth", "D"),
    (268, "Prashant Solanki", "D"), (269, "Raghav Goyal", "D"), (270, "Saurabh Kumar", "D"),
    (271, "Prince Choudhary", "D"), (272, "Vignesh Puthur", "D"), (273, "Jhathavedh Subramanyan", "D"),
    (274, "Himanshu Sharma", "D"), (275, "Bernard Scholtz", "D"), (276, "Mark Watt", "D"),
    (277, "Nosthush Kenjige", "D"), (278, "Assad Vala", "D"), (279, "Brian Masaba", "D"),
    (280, "Alpesh Ramjani", "D"),

    (281, "Priyansh Arya", "E"), (282, "Agni Chopra", "E"), (283, "Rohan Kunnummal", "E"),
    (284, "Sachin Baby", "E"), (285, "Atharva Taide", "E"), (286, "Ankit Kumar", "E"),
    (287, "Himmat Singh", "E"), (288, "Pukhraj Mann", "E"), (289, "Shubham Khajuria", "E"),
    (290, "Salman Nizar", "E"), (291, "Sahil Parakh", "E"), (292, "B. Aparajith", "E"),
    (293, "Jacob Bethell", "E"), (294, "Teddy Bishop", "E"), (295, "Akshay Wadkar", "E"),
    (296, "Eknath Kerkar", "E"), (297, "Vivek Singh", "E"), (298, "K.S. Rathore", "E"),
    (299, "Mohammed Azharuddeen", "E"), (300, "Pradosh Ranjan Paul", "E"), (301, "Het Patel", "E"),
    (302, "Yashovardhan Parantap", "E"), (303, "Jewel Andrew", "E"), (304, "Tadiwanashe Marumani", "E"),
    (305, "Lahiru Udara", "E"), (306, "Bipin Saurabh", "E"), (307, "Tom Blundell", "E"),
    (308, "Sadeera Samarawickrama", "E"), (309, "Arshin Kulkarni", "E"), (310, "Rajvardhan Hangargekar", "E"),
    (311, "Manoj Bhandage", "E"), (312, "Atit Sheth", "E"), (313, "Shams Mulani", "E"),
    (314, "Pulkit Narang", "E"), (315, "Chirag Jani", "E"), (316, "Ninad Rathva", "E"),
    (317, "Sanjay Yadav", "E"), (318, "Macneil Noronha", "E"), (319, "Auqib Dar", "E"),
    (320, "Matthew Boast", "E"), (321, "Nathan Smith", "E"), (322, "Nipun Dhananjaya", "E"),
    (323, "Kwena Maphaka", "E"), (324, "Akash Deep", "E"), (325, "Ishan Porel", "E"),
    (326, "Vasuki Koushik", "E"), (327, "Rajan Kumar", "E"), (328, "Mohit Avasthi", "E"),
    (329, "Mukhtar Hussain", "E"), (330, "Prince Yadav", "E"), (331, "M. Mohammed", "E"),
    (332, "Gurnoor Brar", "E"), (333, "William O'Rourke", "E"), (334, "Xavier Bartlett", "E"),
    (335, "Blessing Muzarabani", "E"), (336, "Andrew Tye", "E"), (337, "Zeeshan Ansari", "E"),
    (338, "Shiva Singh", "E"), (339, "Saumy Pandey", "E"), (340, "Shubham Sharma", "E"),
    (341, "Dharmendrasinh Jadeja", "E"), (342, "Harsh Dubey", "E"), (343, "Lalith Mohan", "E"),
    (344, "Tejas Baroka", "E"), (345, "Prashant Chopra", "E"), (346, "Izharulhaq Naveed", "E"),
    (347, "Traveen Mathew", "E"), (348, "Faisal Khan", "E"), (349, "Peter Hatzoglou", "E"),
    (350, "Khary Pierre", "E"),
]
